version: '3.4'

services:
  doubanapi:
    image: caryyu/douban-openapi-server
    ports:
      - 5000:5000
  mongodb:
    image: mongo:5.0.5
    ports:
      - 27017:27017
    volumes:
      - /f/hippocampus:/data/db
  externalhippocampus:
    image: externalhippocampus
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:8080
