version: '3.9'

services:
  mongodb:
    image: mongo:5.0.9
    ports:
      - 27017:27017
    volumes:
      - /mnt/sdb2/exhippocampus:/data/db
  exhippocampus:
    image: exhippocampus
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 30000:30000
